osx_image: xcode611
language: objective-c
before_install: gem install cocoapods xcpretty -N
cache: cocoapods
podfile: Example/Podfile
script:
- export LC_CTYPE=en_US.UTF-8
- export LANG=en_US.UTF-8
- set -o pipefail && xcodebuild -workspace Example/SSDynamicTextExample.xcworkspace
  -scheme SSDynamicTextExample -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" 
  clean test ONLY_ACTIVE_ARCH=NO | xcpretty -c
notifications:
  slack:
    secure: AKWERCmo9jI3/ZHsDo0RHT5lwMVmpTjEzmy8r4rvyFigu+PQFzXefrdIu12qyVM3kL+of0bReHjDg7BM12fguaCJtUVdLgZbbqIqsZnbdeqXrS1s1FBl0+9ACBIlznOw9B83Y+4QtXnwFSkfpvXBJXG2B2l7CiJc8k9LHd7V2Ew=
