comment:
    layout: "header, changes, diff, sunburst"
coverage:
    ignore:
        - "Example/*"
        - "Applications/*"
    status:
        patch:
            default:
                target: 90%
        project:
            default:
                target: 90%
