comment:
    layout: header, changes, diff, sunburst
coverage:
    ignore:
        - Example/.*
        - Applications/.*
    status:
        patch:
            default:
            target: '80'
        project:
            default:
            target: '80'
